### ISSUE TITLE
Make sshdeploy also available as a dotnet CLI tool extension

### ISSUE THREAD

**Issue by raffaeler** [unosquare/sshdeploy#1]
This is just a suggestion.
Since the dotnet CLI can be extended, you could make it available on nuget to extend the dotnet CLI.
A possible usage would be:
dotnet sshdeploy ...

Going further, the sshdeploy could also trigger the SCD publishing (Self Contained Deployment) when you don't want to install the runtime or the sdk on the target linux machine.

**Comment by geoperez** [comment]
Sounds cool, let me check it.

**Comment by raffaeler** [comment]
If you need some help, please let me know :)

**Comment by geoperez** [comment]
Hi @raffaeler do you have any link to the documentation on how extend dotnet CLI? I found nothing.

**Comment by geoperez** [comment]
Possible link: https://docs.microsoft.com/en-us/dotnet/core/tools/extensibility

**Comment by raffaeler** [comment]
Exactly, the link is correct.

**Comment by geoperez** [comment]
Pull request created #2

**Comment by geoperez** [comment]
Hi @raffaeler any feedback?

**Comment by geoperez** [comment]
Resolved.
