### ISSUE TITLE
async main is not available

### ISSUE THREAD

**Issue by k3z0** [unosquare/sshdeploy#15]
**Describe the bug**
When you try to publish an app that uses **async main**, ssh deploy generates the next error:

    error CS8107: Feature 'async main' is not available in C# 7.0.

**Note:** It seems like if you don't include the **LangVersion** tag then ssh deploy uses C# 7.0 by default for publishing the app.

![imagen](https://user-images.githubusercontent.com/5455304/55584180-e2d84c80-56e0-11e9-896c-c6991adef7c7.png)

**Comment by geoperez** [comment]
@k3z0 can you check again?

**Comment by k3z0** [comment]
This happens too in VS 2017 if you don't specify the appropriate LangVersion:

![imagen](https://user-images.githubusercontent.com/5455304/57336865-15fd6980-70ed-11e9-97d4-77309b411237.png)

**Note**: In VS 2019 it seems to be fixed.

**Comment by geoperez** [comment]
Well, that is expected because the project is not using C# 7.3! Closing.
