### ISSUE TITLE
Use rsync where available

### ISSUE THREAD

**Issue by daveyostcom** [unosquare/sshdeploy#16]
Invoking the [rsync](https://rsync.samba.org/features.html) command when available (on both source and destination), would make transfers 100x faster. Rsync copies only the portions of files that have changed and can be directed to delete all files not wanted on the destination.

**Comment by geoperez** [comment]
Sounds like a good idea!

**Comment by daveyostcom** [comment]
Something like this:
```
project=Thingy
cd $project
bin=bin/Debug/netcoreapp2.2/linux-arm
dest=pi@pi.local:deployments/$project
chmod +x $bin/$project
rsync -a --progress --partial $bin/  $dest
rsync -a --progress --partial pathToOtherStuff/  $dest
```

**Comment by daveyostcom** [comment]
This seems to work fine for me on my Mac with dotnet installed via brew:
```
project=Thingy
cd $project
bin=bin/Debug/netcoreapp2.2/linux-arm/publish/
dest=pi@pi.local:deployments/$project
dotnet publish
chmod +x $bin/$project
rsync -a --delete  $bin/  $dest
```
Other [rsync](https://rsync.samba.org/features.html) arguments that can be useful are:
```
 --progress
 --partial
```
