### ISSUE TITLE
Feature request: automatically chmod executable for deployments

### ISSUE THREAD

**Issue by gingters** [unosquare/sshdeploy#18]
When I deploy a .net core self-contained project onto my Raspberry Pi,
I always have to `chmod +x myProject && ./myProject` on the Pi, as the executable is not marked as an executable file after the ssh copy of the project.

This is, however, only a minor inconvenience. That said, if it would be possible to add a chmod call to mark the executable as such without a lot of effort (i.e. the executable could be easily found from msbuild properties and the call could easily be added), that would be a nice improvement.

**Comment by k3z0** [comment]
Hi @gingters 

We already released a new version of ssh-deploy that supports adding execute permission to the deployed files. You only need to use the **SshDeployExecutePermission** tag in your project's csproj file:

```console
<SshDeployExecutePermission>true</SshDeployExecutePermission>
```
Or use the appropriate command line argument:

```console
dotnet-sshdeploy push ... -x true
```

Could you please update ssh-deploy and test this new feature.

```console
dotnet tool update -g dotnet-sshdeploy
```

Thanks.

**Comment by gingters** [comment]
Oh, wow. I must have missed that in the docs. Sorry.
That works like a charm. Thanks!
