### ISSUE TITLE
Optimize file pushing for only files that changed

### ISSUE THREAD

**Issue by vbisbest** [unosquare/sshdeploy#26]
A default MVC app will push almost 400 files in "self-contained" mode.  THis happens on every build and takes a minute every time.   It would be great if there could be some file compare or datetime stamp logic to skip the 390 files that did not change.

**Comment by geoperez** [comment]
That is a good idea!

**Comment by vbisbest** [comment]
One more thought since timestamp could be tricky (system time vs device time etc).  You could add a csproj option to ignore the runtime files if they already exist on the device.  E.g. Skip everything that is "Microsoft.*" or "System.*".  That way only a few files would be copied every time.

**Comment by geoperez** [comment]
@jpalcala did you get a chance to check this issue?
