### ISSUE TITLE
Support for VbProj

### ISSUE THREAD

**Issue by ghost** [unosquare/sshdeploy#29]
**Is your feature request related to a problem? Please describe.**
I wanted to use the Proj file Solution to push the binaries. Sadly it is not recognizing a VbProj file.
The error I'm getting is "No csproj file was found"
**Describe the solution you'd like**
It should be searching for CsProj and VbProj files.

**Comment by geoperez** [comment]
Sure thing, we can check it

**Comment by geoperez** [comment]
You can check the new version 0.4.0 at https://www.nuget.org/packages/dotnet-sshdeploy
