### ISSUE TITLE
Deploying ASP.NET Core project fails

### ISSUE THREAD

**Issue by marinasundstrom** [unosquare/sshdeploy#4]
Cannot deploy a ASP.NET Core project with Sdk "Microsoft.NET.Sdk.Web" with this tool.

The problem is in ```Swan``` and is tracked here: unosquare/swan#96

**Comment by marinasundstrom** [comment]
Fix in pull request: unosquare/swan#97

**Comment by marinasundstrom** [comment]
When will you release a new package?

**Comment by geoperez** [comment]
Yes

**Comment by geoperez** [comment]
Can you test https://www.nuget.org/packages/dotnet-sshdeploy/0.2.0 ?

**Comment by marinasundstrom** [comment]
Installed, ran on project with Sdk "Microsoft.NET.Sdk.Web", and got:

```
Unhandled Exception: System.ArgumentException: Project file is not of the new .csproj type.
   at Unosquare.Swan.Components.CsProjFile`1..ctor(Stream stream, Boolean leaveOpen)
   at Unosquare.Labs.SshDeploy.Program.Main(String[] args)
```

Are the changes even in the Swan package?

**Comment by geoperez** [comment]
@jpalcala can you check the issue please?

**Comment by marinasundstrom** [comment]
@geoperez @jpalcala I checked with ILSpy and they aren't in Swan 0.28.0.

**Comment by jpalcala** [comment]
Hi @robertsundstrom 
Sorry for the inconvenience, but thankfully this issue has now been resolved. I have already tested it myself nevertheless I encourage you to do the same. 
 
This is our newest version: https://www.nuget.org/packages/dotnet-sshdeploy/0.2.1

**Comment by marinasundstrom** [comment]
@jpalcala It works. Thanks!
