### ISSUE TITLE
Publish breaks application

### ISSUE THREAD

**Issue by LINKIT-HIVE** [unosquare/sshdeploy#9]
**Describe the bug**
When I publish after a succesfull build my dotnet application does not execute anymore.

The following exception is thrown:

> pi@pibot01:~/publish $ ./PiCore
> PiCore: /root/coresetup/src/corehost/cli/fxr/fx_muxer.cpp:416: static pal::strin                                                                                                         g_t fx_muxer_t::resolve_fx_dir(host_mode_t, const pal::string_t &, const runtime                                                                                                         _config_t &, const pal::string_t &, const int &): Assertion `mode != host_mode_t                                                                                                         ::standalone' failed.
> Aborted

**To Reproduce**
My initial deploy was with Putty pscp.exe. 
Later I implemented dotnet-sshdeploy which published the changes.

**Expected behavior**
I expect an update of my application.

**Comment by geoperez** [comment]
Did you use dotnet publish command and then scopy the entire publish folder?

**Comment by LINKIT-HIVE** [comment]
I Use VS2017 Enterprise. I referenced the library and changed my project.

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <SshDeployHost>192.168.1.28</SshDeployHost>
    <!--<SshDeployClean />-->
    <SshDeployTargetPath>/home/pi/publish</SshDeployTargetPath>
    <SshDeployUsername>pi</SshDeployUsername>
    <SshDeployPassword>raspberry</SshDeployPassword>
    <RunPostBuildEvent>OnBuildSuccess</RunPostBuildEvent>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="dotnet-sshdeploy" Version="0.2.1" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.8" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.0.3" />
    <PackageReference Include="Unosquare.Raspberry.IO" Version="0.14.0" />
    <PackageReference Include="Unosquare.RaspberryIO.Peripherals" Version="0.1.0" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.4" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="dotnet-sshdeploy" Version="0.2.1" />
  </ItemGroup>

  <Target Condition="$(BuildingInsideSshDeploy) ==''" Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="cd $(ProjectDir)" />
    <Exec Command="dotnet sshdeploy push" />
  </Target>
</Project>
```

When I executed my code on the PI the exception is thrown.

**Comment by geoperez** [comment]
@jpalcala do you notice any issue?

**Comment by israelramosm** [comment]
@CentricStraaten There is a new version of sshdeploy you can download from the dotnet tool by running `dotnet tool install -g dotnet-sshdeploy` with that you can use it as a command `dotnet-sshdeploy push` and removed the `DotNetCliToolReference` from your csproj. Can you try the new version and tell us if the bug is resolved?

**Comment by israelramosm** [comment]
Closing because no response
